# Google App Engine configuration
runtime: python39

env_variables:
  GOOGLE_API_KEY: "your api key"

automatic_scaling:
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
