services:
  - type: web
    name: smart-ai-resume-analyzer
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: A4F_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /_stcore/health